In [1]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\aryan\anaconda3\lib\site-packages (5.0.1)

In [2]:
!pip install unidecode

Requirement already satisfied: unidecode in c:\users\aryan\anaconda3\lib\site-packages (1.2.0)

In [3]:
import numpy as np
import pandas as pd
import pyodbc
from unidecode import unidecode

In [4]:
# lets establish connection to ms-sql server.

server="LAPTOP-JV7LGN7I\SQLEXPRESS"
database="campusx_project2"

connection_string=(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

conn = pyodbc.connect(connection_string)

In [5]:
query="select * from olist_customers_dataset"
customers= pd.read_sql(query, conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\1667547915.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers= pd.read_sql(query, conn)

### olist_customers_datase

In [7]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,sao paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,rio de janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,taboao da serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,osasco,SP

In [8]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [9]:
customers.sample(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
39652,6680ee2ede756c3fa20357158525bc98,e238fba997eec80e48bf8d8689877d89,9750,sao bernardo do campo,SP
47278,7a0c5469cba3eb88c664cbb7d680ee56,2b161eaf4956b131691842e87b3c39c7,13278,valinhos,SP
74410,bee1e23957cf75da376d033c4e2ba724,34c43e7170995ec125afcfefda28b657,87200,cianorte,PR
93464,f03d501fcffc9f7e97ab7c8f07c6fd89,1e1ee664f240408d29680ac7d07665a1,18071,sorocaba,SP
11637,1de9b9d609d626f82db0533fb400e84b,aba84ac9f5f1fa02826b0f72a6c96c3b,90870,porto alegre,RS
93900,f14c14c6129468981840deb6b0474ba0,0b366bcd927bbe310de8ea00f1cf5bbf,13145,paulinia,SP
13458,22920e925fcbdd68ef776651f8c53cc3,891778c525b6b0b4b973991aaa00f622,29500,alegre,ES
29851,4d076b22079be9bc624fa921a1b6b7f2,d507f95c1428c6ef2990ac45fd0b2382,29047,vitoria,ES
82144,d2dcd733958599094bae3cb1397babe4,7a95ffe480d2a7b927f354684aa39c06,38770,joao pinheiro,MG
47347,7a366704a9562a585054e6a2c02f33b8,e6d38df64bcfa3003724ccb7ffed6959,69088,manaus,AM

In [10]:
# capitalizing first alphabet of each word for city.
customers["customer_city"]= customers["customer_city"].str.title()

In [11]:
customers["customer_id"].nunique()

99441

In [12]:
customers["customer_unique_id"].nunique()

96096

In [13]:
sum(customers["customer_id"]==customers["customer_unique_id"])

0

### geoloacation dataset

In [15]:
query="select * from olist_geolocation_dataset"
geo= pd.read_sql(query, conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\3619535398.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  geo= pd.read_sql(query, conn)

In [16]:
geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,22260,-22.949663,-43.184895,rio de janeiro,RJ
1,22220,-22.931046,-43.174862,rio de janeiro,RJ
2,22251,-22.943998,-43.182579,rio de janeiro,RJ
3,22260,-22.950054,-43.190887,rio de janeiro,RJ
4,22240,-22.932543,-43.182613,rio de janeiro,RJ
...,...,...,...,...,...
1000158,99950,-28.068640,-52.010704,tapejara,RS
1000159,99900,-27.877125,-52.224884,getulio vargas,RS
1000160,99950,-28.071856,-52.014717,tapejara,RS
1000161,99980,-28.388931,-51.846870,david canabarro,RS
1000162,99950,-28.070103,-52.018658,tapejara,RS

In [17]:
geo["geolocation_city"]=geo["geolocation_city"].str.title()

In [18]:
geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,22260,-22.949663,-43.184895,Rio De Janeiro,RJ
1,22220,-22.931046,-43.174862,Rio De Janeiro,RJ
2,22251,-22.943998,-43.182579,Rio De Janeiro,RJ
3,22260,-22.950054,-43.190887,Rio De Janeiro,RJ
4,22240,-22.932543,-43.182613,Rio De Janeiro,RJ
...,...,...,...,...,...
1000158,99950,-28.068640,-52.010704,Tapejara,RS
1000159,99900,-27.877125,-52.224884,Getulio Vargas,RS
1000160,99950,-28.071856,-52.014717,Tapejara,RS
1000161,99980,-28.388931,-51.846870,David Canabarro,RS
1000162,99950,-28.070103,-52.018658,Tapejara,RS

In [19]:
geo.duplicated().sum()

262154

In [20]:
geo.drop_duplicates(inplace=True)

In [21]:
geo.shape

(738009, 5)

In [22]:
geo.drop(columns=["geolocation_lat","geolocation_lng"], inplace=True)

In [23]:
geo["geolocation_city"].sample(10)

372514               Sao Paulo
325512               Sao Paulo
406411               Sao Paulo
646203    São Joaquim Da Barra
453552               Sao Paulo
890090               Arapongas
714285          Rio De Janeiro
369725               Sao Paulo
246424                 Valenca
144915                 Mantena
Name: geolocation_city, dtype: object

In [24]:
print(geo["geolocation_city"].nunique())

8011

In [25]:
geo["geolocation_city"]=geo["geolocation_city"].apply(lambda x: unidecode(x))

In [26]:
geo

        geolocation_zip_code_prefix geolocation_city geolocation_state
0                             22260   Rio De Janeiro                RJ
1                             22220   Rio De Janeiro                RJ
2                             22251   Rio De Janeiro                RJ
3                             22260   Rio De Janeiro                RJ
4                             22240   Rio De Janeiro                RJ
...                             ...              ...               ...
1000155                       99965       Agua Santa                RS
1000156                       99950         Tapejara                RS
1000157                       99950         Tapejara                RS
1000158                       99950         Tapejara                RS
1000161                       99980  David Canabarro                RS

[738009 rows x 3 columns]

In [27]:
print(geo["geolocation_city"].nunique())

5969

In [28]:
def contains_number(s):
    return any(i.isdigit() for i in str(s))

In [29]:
geo[geo["geolocation_city"].apply(contains_number)]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
94726,29735,Quilometro 14 Do Mutum,ES
95291,29735,Quilometro 14 Do Mutum,ES
282579,57010,Maceia3,AL
685352,17970,Sao Joao Do Pau D%26Apos%3Balho,SP
786179,71880,Riacho Fundo 2,DF
823386,78278,Lambari D%26Apos%3Boeste,MT
896733,87365,4O. Centenario,PR
896977,87365,4o Centenario,PR
897217,87365,4o Centenario,PR
977775,96130,Colonia Z-3,RS
977787,96130,Colonia Z-3,RS
977813,96130,Colonia Z-3,RS

In [30]:
import re
def remove_number(s):
    return re.sub(r'\d+','',str(s))

In [31]:
geo["geolocation_city"]=geo["geolocation_city"].apply(remove_number)

In [32]:
geo[geo["geolocation_city"].apply(contains_number)]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [33]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
684947,17970,Sao Joao Do Pau D'Alho,SP
684969,17970,Sao Joao Do Pau D'Alho,SP
685047,17970,Sao Joao Do Pau D'Alho,SP
685079,17970,Sao Joao Do Pau D Alho,SP
685164,17970,Sao Joao Do Pau D Alho,SP
685215,17970,Sao Joao Do Pau D'Alho,SP
685224,17970,Sao Joao Do Pau D'Alho,SP
685234,17970,Sao Joao Do Pau Dalho,SP
685280,17970,Sao Joao Do Pau D'Alho,SP
685328,17970,Sao Joao Do Pau Dalho,SP
685352,17970,Sao Joao Do Pau D%Apos%Balho,SP
685448,17970,Sao Joao Do Pau D Alho,SP
685466,17970,Sao Joao Do Pau D'Alho,SP
685473,17970,Sao Joao Do Pau D'Alho,SP
685638,17970,Sao Joao Do Pau D'Alho,SP

In [34]:
geo["geolocation_city"]=geo["geolocation_city"].str.replace("'","",regex=False)

In [35]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
684947,17970,Sao Joao Do Pau DAlho,SP
684969,17970,Sao Joao Do Pau DAlho,SP
685047,17970,Sao Joao Do Pau DAlho,SP
685079,17970,Sao Joao Do Pau D Alho,SP
685164,17970,Sao Joao Do Pau D Alho,SP
685215,17970,Sao Joao Do Pau DAlho,SP
685224,17970,Sao Joao Do Pau DAlho,SP
685234,17970,Sao Joao Do Pau Dalho,SP
685280,17970,Sao Joao Do Pau DAlho,SP
685328,17970,Sao Joao Do Pau Dalho,SP
685352,17970,Sao Joao Do Pau D%Apos%Balho,SP
685448,17970,Sao Joao Do Pau D Alho,SP
685466,17970,Sao Joao Do Pau DAlho,SP
685473,17970,Sao Joao Do Pau DAlho,SP
685638,17970,Sao Joao Do Pau DAlho,SP

In [36]:
geo.duplicated().sum()

718393

In [37]:
geo.shape

(738009, 3)

In [38]:
geo[geo["geolocation_city"].str.startswith("*")]

       geolocation_zip_code_prefix geolocation_city geolocation_state
851430                       81470         * Cidade                PR

In [39]:
geo["geolocation_city"]=geo["geolocation_city"].str.replace("*","",regex=False)

In [40]:
geo[geo["geolocation_city"].str.startswith("*")]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [41]:
geo[geo["geolocation_city"].str.startswith("...")]

      geolocation_zip_code_prefix    geolocation_city geolocation_state
81206                       28930  ...Arraial Do Cabo                RJ

In [42]:
geo["geolocation_city"]=geo["geolocation_city"].str.replace("...","",regex=False)

In [43]:
geo[geo["geolocation_city"].str.startswith("...")]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [44]:
def keep_only_text(x):
    if pd.isna(x):
        return x
    # remove everything except alphabets and spaces
    return re.sub(r"[^A-Za-z\s]", "", str(x)).strip()

In [45]:
geo["geolocation_city"]= geo["geolocation_city"].apply(keep_only_text)

In [46]:
geo["geolocation_city"]

0           Rio De Janeiro
1           Rio De Janeiro
2           Rio De Janeiro
3           Rio De Janeiro
4           Rio De Janeiro
                ...
1000155         Agua Santa
1000156           Tapejara
1000157           Tapejara
1000158           Tapejara
1000161    David Canabarro
Name: geolocation_city, Length: 738009, dtype: object

In [47]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
684947,17970,Sao Joao Do Pau DAlho,SP
684969,17970,Sao Joao Do Pau DAlho,SP
685047,17970,Sao Joao Do Pau DAlho,SP
685079,17970,Sao Joao Do Pau D Alho,SP
685164,17970,Sao Joao Do Pau D Alho,SP
685215,17970,Sao Joao Do Pau DAlho,SP
685224,17970,Sao Joao Do Pau DAlho,SP
685234,17970,Sao Joao Do Pau Dalho,SP
685280,17970,Sao Joao Do Pau DAlho,SP
685328,17970,Sao Joao Do Pau Dalho,SP
685352,17970,Sao Joao Do Pau DAposBalho,SP
685448,17970,Sao Joao Do Pau D Alho,SP
685466,17970,Sao Joao Do Pau DAlho,SP
685473,17970,Sao Joao Do Pau DAlho,SP
685638,17970,Sao Joao Do Pau DAlho,SP

In [48]:
geo["geolocation_city"]= geo["geolocation_city"].str.replace("Sao Joao Do Pau D Alho","Sao Joao Do Pau DAlho")

In [49]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
684947,17970,Sao Joao Do Pau DAlho,SP
684969,17970,Sao Joao Do Pau DAlho,SP
685047,17970,Sao Joao Do Pau DAlho,SP
685079,17970,Sao Joao Do Pau DAlho,SP
685164,17970,Sao Joao Do Pau DAlho,SP
685215,17970,Sao Joao Do Pau DAlho,SP
685224,17970,Sao Joao Do Pau DAlho,SP
685234,17970,Sao Joao Do Pau Dalho,SP
685280,17970,Sao Joao Do Pau DAlho,SP
685328,17970,Sao Joao Do Pau Dalho,SP
685352,17970,Sao Joao Do Pau DAposBalho,SP
685448,17970,Sao Joao Do Pau DAlho,SP
685466,17970,Sao Joao Do Pau DAlho,SP
685473,17970,Sao Joao Do Pau DAlho,SP
685638,17970,Sao Joao Do Pau DAlho,SP

In [50]:
geo.duplicated().sum()

718397

In [51]:
geo.drop_duplicates(inplace=True)

In [52]:
geo

       geolocation_zip_code_prefix      geolocation_city geolocation_state
0                            22260        Rio De Janeiro                RJ
1                            22220        Rio De Janeiro                RJ
2                            22251        Rio De Janeiro                RJ
4                            22240        Rio De Janeiro                RJ
6                            22230        Rio De Janeiro                RJ
...                            ...                   ...               ...
999774                       99955          Vila Langaro                RS
999780                       99970               Ciriaco                RS
999786                       99910      Floriano Peixoto                RS
999803                       99920              Erebango                RS
999846                       99952  Santa Cecilia Do Sul                RS

[19612 rows x 3 columns]

In [53]:
geo["geolocation_city"].nunique()

5962

In [54]:
#  PERFORMING THE SAME STEP FOR CUSTOMER TABLE FOR CITY COLUMN
customers["customer_city"]=customers["customer_city"].apply(lambda x: unidecode(x))

In [55]:
customers["customer_city"]=customers["customer_city"].apply(keep_only_text)

In [56]:
customers.duplicated().sum()

0

In [57]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,Osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,Itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,Nova Venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,Mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,Sao Paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,Parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,Rio De Janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,Taboao Da Serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,Alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,Osasco,SP

### olist_products_dataset

In [59]:
query ="select * from olist_products_dataset"
products= pd.read_sql(query, conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\3138657782.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products= pd.read_sql(query, conn)

In [60]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625,20,17,13
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300,40,40,40
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700,16,19,16
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400,27,7,27
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700,31,13,20
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083,12,2,7

In [61]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [62]:
products=products.drop(columns=['product_name_lenght',
       'product_description_lenght',  'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'])

In [63]:
products["product_category_name"].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', None,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

In [64]:
query="select* from product_category_name_translation"
product_name=pd.read_sql(query,conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\427460703.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  product_name=pd.read_sql(query,conn)

In [65]:
product_name

                product category     product category in english
0           product_category_name  product_category_name_english
1                    beleza_saude                  health_beauty
2          informatica_acessorios          computers_accessories
3                      automotivo                           auto
4                 cama_mesa_banho                 bed_bath_table
..                            ...                            ...
67                         flores                        flowers
68             artes_e_artesanato          arts_and_craftmanship
69                fraldas_higiene            diapers_and_hygiene
70  fashion_roupa_infanto_juvenil      fashion_childrens_clothes
71             seguros_e_servicos          security_and_services

[72 rows x 2 columns]

In [66]:
product_name.drop(index=0,inplace=True)

In [67]:

# Strip spaces and replace spaces with underscores
product_name.columns = product_name.columns.str.strip().str.replace(' ', '_')

In [68]:
print(products["product_category_name"].nunique())
print(product_name["product_category"].nunique())

73
71

In [69]:
# 71 common in both the table ??
# product - a,b,c,d   --4 
# product_name - a, b, e,f   --4

In [70]:
# lets find the category that is in product table but not in product_name table
product_name[~product_name["product_category"].isin(products["product_category_name"])]

Empty DataFrame
Columns: [product_category, product_category_in_english]
Index: []

In [71]:
products[~products["product_category_name"].isin(product_name["product_category"])]["product_category_name"].unique()

array([None, 'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'],
      dtype=object)

In [72]:
product_name.sort_values(by=["product_category"])["product_category"].unique()

array(['agro_industria_e_comercio', 'alimentos', 'alimentos_bebidas',
       'artes', 'artes_e_artesanato', 'artigos_de_festas',
       'artigos_de_natal', 'audio', 'automotivo', 'bebes', 'bebidas',
       'beleza_saude', 'brinquedos', 'cama_mesa_banho', 'casa_conforto',
       'casa_conforto_2', 'casa_construcao', 'cds_dvds_musicais',
       'cine_foto', 'climatizacao', 'consoles_games',
       'construcao_ferramentas_construcao',
       'construcao_ferramentas_ferramentas',
       'construcao_ferramentas_iluminacao',
       'construcao_ferramentas_jardim',
       'construcao_ferramentas_seguranca', 'cool_stuff', 'dvds_blu_ray',
       'eletrodomesticos', 'eletrodomesticos_2', 'eletronicos',
       'eletroportateis', 'esporte_lazer', 'fashion_bolsas_e_acessorios',
       'fashion_calcados', 'fashion_esporte', 'fashion_roupa_feminina',
       'fashion_roupa_infanto_juvenil', 'fashion_roupa_masculina',
       'fashion_underwear_e_moda_praia', 'ferramentas_jardim', 'flores',
       'fraldas_higiene', 'industria_comercio_e_negocios',
       'informatica_acessorios', 'instrumentos_musicais', 'la_cuisine',
       'livros_importados', 'livros_interesse_geral', 'livros_tecnicos',
       'malas_acessorios', 'market_place', 'moveis_colchao_e_estofado',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'moveis_decoracao', 'moveis_escritorio', 'moveis_quarto',
       'moveis_sala', 'musica', 'papelaria', 'pcs', 'perfumaria',
       'pet_shop', 'portateis_casa_forno_e_cafe', 'relogios_presentes',
       'seguros_e_servicos', 'sinalizacao_e_seguranca',
       'tablets_impressao_imagem', 'telefonia', 'telefonia_fixa',
       'utilidades_domesticas'], dtype=object)

In [73]:
product_name[product_name["product_category"]=="pcs"]

   product_category product_category_in_english
54              pcs                   computers

In [74]:
product_name[product_name["product_category"]=="portateis_casa_forno_e_cafe"]

               product_category            product_category_in_english
64  portateis_casa_forno_e_cafe  small_appliances_home_oven_and_coffee

In [75]:
products=pd.merge(products, product_name,left_on="product_category_name", right_on="product_category",how="left")

In [76]:
products

,product_id,product_category_name,product_photos_qty,product_category,product_category_in_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,1.0,perfumaria,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1.0,artes,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,1.0,esporte_lazer,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,1.0,bebes,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,4.0,utilidades_domesticas,housewares
...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,2.0,moveis_decoracao,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1.0,construcao_ferramentas_iluminacao,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,2.0,informatica_acessorios,computers_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table

In [77]:
products[products["product_category_name"]=="portateis_cozinha_e_preparadores_de_alimentos"]

,product_id,product_category_name,product_photos_qty,product_category,product_category_in_english
5821,6fd83eb3e0799b775e4f946bd66657c0,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
7325,5d923ead886c44b86845f69e50520c3e,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
8819,bed164d9d628cf0593003389c535c6e0,portateis_cozinha_e_preparadores_de_alimentos,2.0,NaN,NaN
11039,1220978a08a6b29a202bc015b18250e9,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
14266,ae62bb0f95af63d64eae5f93dddea8d3,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
16182,1954739d84629e7323a4295812a3e0ec,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,NaN
17800,c7a3f1a7f9eef146cc499368b578b884,portateis_cozinha_e_preparadores_de_alimentos,5.0,NaN,NaN
18610,7afdd65f79f63819ff5bee328843fa37,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
26890,a4756663d007b0cd1af865754d08d968,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,NaN
29919,cb9d764f38ee4d0c00af64d5c388f837,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN

In [78]:
products.loc[products["product_category_name"]=="pc_gamer","product_category_in_english"]="computers"
products.loc[products["product_category_name"]=="portateis_cozinha_e_preparadores_de_alimentos", "product_category_in_english"]="small_appliances_home_oven_and_coffee"

In [79]:
products[products["product_category_name"]=="portateis_cozinha_e_preparadores_de_alimentos"]

,product_id,product_category_name,product_photos_qty,product_category,product_category_in_english
5821,6fd83eb3e0799b775e4f946bd66657c0,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
7325,5d923ead886c44b86845f69e50520c3e,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
8819,bed164d9d628cf0593003389c535c6e0,portateis_cozinha_e_preparadores_de_alimentos,2.0,NaN,small_appliances_home_oven_and_coffee
11039,1220978a08a6b29a202bc015b18250e9,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
14266,ae62bb0f95af63d64eae5f93dddea8d3,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
16182,1954739d84629e7323a4295812a3e0ec,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,small_appliances_home_oven_and_coffee
17800,c7a3f1a7f9eef146cc499368b578b884,portateis_cozinha_e_preparadores_de_alimentos,5.0,NaN,small_appliances_home_oven_and_coffee
18610,7afdd65f79f63819ff5bee328843fa37,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
26890,a4756663d007b0cd1af865754d08d968,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,small_appliances_home_oven_and_coffee
29919,cb9d764f38ee4d0c00af64d5c388f837,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee

In [80]:
products[products["product_category_name"]=="pc_gamer"]

,product_id,product_category_name,product_photos_qty,product_category,product_category_in_english
1628,0105b5323d24fc655f73052694dbbb3a,pc_gamer,4.0,NaN,computers
7478,6727051471a0fc4a0e7737b57bff2549,pc_gamer,3.0,NaN,computers
16930,dbe520fb381ad695a7e1f2807d20c765,pc_gamer,6.0,NaN,computers

In [81]:
products["product_category_name"]=products["product_category_in_english"]

In [82]:
products

,product_id,product_category_name,product_photos_qty,product_category,product_category_in_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,1.0,perfumaria,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,art,1.0,artes,art
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,1.0,esporte_lazer,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,baby,1.0,bebes,baby
4,9dc1a7de274444849c219cff195d0b71,housewares,4.0,utilidades_domesticas,housewares
...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,2.0,moveis_decoracao,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,1.0,construcao_ferramentas_iluminacao,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,1.0,cama_mesa_banho,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,2.0,informatica_acessorios,computers_accessories
32950,106392145fca363410d287a815be6de4,bed_bath_table,1.0,cama_mesa_banho,bed_bath_table

In [83]:
products.drop(columns=["product_category","product_category_in_english"],inplace=True)

In [84]:
products

,product_id,product_category_name,product_photos_qty
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,1.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,1.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,1.0
3,cef67bcfe19066a932b7673e239eb23d,baby,1.0
4,9dc1a7de274444849c219cff195d0b71,housewares,4.0
...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,2.0
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,1.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,1.0
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,2.0
32950,106392145fca363410d287a815be6de4,bed_bath_table,1.0

###  olist_sellers_dataset.csv:

In [86]:
query=("select* from olist_sellers_dataset")
seller=pd.read_sql(query,conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\3715963524.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  seller=pd.read_sql(query,conn)

In [87]:
seller

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [88]:
seller["seller_city"]=seller["seller_city"].str.title()

In [89]:
seller

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,Sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,Palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,Sao Paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,Pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,Taubate,SP

In [90]:
seller.duplicated().sum()

0

In [91]:
seller[seller["seller_id"].duplicated()]

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [92]:
seller["seller_city"]= seller["seller_city"].apply(keep_only_text)

In [93]:
seller

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,Sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,Palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,Sao Paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,Pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,Taubate,SP

### olist orders dataset

In [95]:
query=("select * from olist_orders_dataset")
orders=pd.read_sql(query,conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\2522622873.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders=pd.read_sql(query,conn)

In [96]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [97]:
orders["order_status"].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [98]:
df=orders.copy()

In [99]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [100]:
orders= orders[
((orders["order_approved_at"]- orders["order_purchase_timestamp"]).dt.total_seconds()/86400>=0) &
((orders['order_delivered_carrier_date'] - orders['order_approved_at']).dt.days >= 0)
]

In [101]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [102]:
orders["order_status"].unique()

array(['delivered', 'shipped', 'canceled'], dtype=object)

In [103]:
orders[(orders["order_status"]=="canceled")& (orders["order_delivered_customer_date"].notna())]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
2921,1950d777989f6a877539f53795b4c3c3,1bccb206de9f0f25adc6871a1bcf77b2,canceled,2018-02-19 19:48:52,2018-02-19 20:56:05,2018-02-20 19:57:13,2018-03-21 22:03:51,2018-03-09
8791,dabf2b0e35b423f94618bf965fcb7514,5cdec0bb8cbdf53ffc8fdc212cd247c6,canceled,2016-10-09 00:56:52,2016-10-09 13:36:58,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30
58266,770d331c84e5b214bd9dc70a10b829d0,6c57e6119369185e575b36712766b0ef,canceled,2016-10-07 14:52:30,2016-10-07 15:07:10,2016-10-11 15:07:11,2016-10-14 15:07:11,2016-11-29
59332,8beb59392e21af5eb9547ae1a9938d06,bf609b5741f71697f65ce3852c5d2623,canceled,2016-10-08 20:17:50,2016-10-09 14:34:30,2016-10-14 22:45:26,2016-10-19 18:47:43,2016-11-30
92636,65d1e226dfaeb8cdc42f665422522d14,70fc57eeae292675927697fe03ad3ff5,canceled,2016-10-03 21:01:41,2016-10-04 10:18:57,2016-10-25 12:14:28,2016-11-08 10:58:34,2016-11-25
94399,2c45c33d2f9cb8ff8b1c86cc28c11c30,de4caa97afa80c8eeac2ff4c8da5b72e,canceled,2016-10-09 15:39:56,2016-10-10 10:40:49,2016-10-14 10:40:50,2016-11-09 14:53:50,2016-12-08

In [104]:
to_remove= orders[(orders["order_status"]=="canceled")& (orders["order_delivered_customer_date"].notna())].index

In [105]:
orders = orders.drop(to_remove)

In [106]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [107]:
orders.duplicated().sum()

0

### olist_order_payments_dataset

In [109]:
query = "select * from olist_order_payments_dataset"
payments= pd.read_sql(query, conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\3494358041.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  payments= pd.read_sql(query, conn)

In [110]:
payments.sort_values(by="payment_sequential", ascending=False)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
53569,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.260000
53572,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.049999
19346,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.019997
46854,ccf804e764ed5650cd8759557269dc13,26,voucher,1,23.100000
94048,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.270000
...,...,...,...,...,...
35375,4ea7a0509e9dc440b977de71fe9128cb,1,credit_card,1,63.000000
35374,a16c1e5c3c877e414d0e584e18ccb860,1,credit_card,2,48.220001
35373,43d15639614829b1cb997af5c0f5f7b0,1,credit_card,2,205.289993
35372,99e5f0c685ca94e5a1c7134b1898bb1a,1,credit_card,3,38.939999
103885,9cca241ed87f1ae14fc65df5c12397a8,1,credit_card,5,364.640015

In [111]:
payments[payments["order_id"]=="fa65dad1b0e818e3ccc5cb0e39231352"]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
3912,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.000000
9788,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.420000
11181,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.030000
19346,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.019997
24446,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.160000
28782,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.710000
31735,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.080000
34026,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.860000
37535,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.510000
39340,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.680000
42791,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.660000
44109,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.020000
46980,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.030000
51283,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.000000
53569,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.260000
53572,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.049999
77830,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.040000
80102,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.950000
83314,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.020000
87998,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.600000
88700,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.110000
89182,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.020000
92346,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.000000
92511,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.860000
94048,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.270000
94131,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.720000
94782,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.730000
97054,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.320000
99627,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.860001

In [112]:
payments[payments["order_id"]=="b81ef226f3fe1789b1e8b2acac839d17"]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
14461,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.330002

In [113]:
payments.drop(columns=["payment_sequential","payment_installments"], inplace=True)

In [114]:
payments

                                order_id payment_type  payment_value
0       a4679a28c7ef85f6277954e4139a3fad  credit_card     112.029999
1       4df87ac1ab76b77699ad16fc5635dbeb  credit_card     153.839996
2       0616463c44a86e8478f9b065e17d7c65  credit_card      53.270000
3       e402e802747c8579d579310e0ec1ddc7       boleto      32.790001
4       db65bf4cccb652a88bf890bd8a69cdc8  credit_card     323.540009
...                                  ...          ...            ...
103881  e1367e30165c3d215977f5caebcc299d  credit_card     514.599976
103882  fd2bcdc6e3cfe79cc7ee426bedb8d467  credit_card      27.340000
103883  686b0cb3ce6ab944288b952ba880080d  credit_card      59.220001
103884  945edc9b56f1a08b87560bf946945f20       boleto     312.489990
103885  9cca241ed87f1ae14fc65df5c12397a8  credit_card     364.640015

[103886 rows x 3 columns]

In [115]:
payments=payments.groupby(["order_id","payment_type"]).sum("payment_value").reset_index()

In [116]:
payments

                                order_id payment_type  payment_value
0       00010242fe8c5a6d1ba2dd792cb16214  credit_card      72.190002
1       00018f77f2f0320c557190d7a144bdd3  credit_card     259.829987
2       000229ec398224ef6ca0657da4fc703e  credit_card     216.869995
3       00024acbcdf0a6daa1e931b038114c75  credit_card      25.780001
4       00042b26cf59d7ce69dfabb4e55b4fd9  credit_card     218.039993
...                                  ...          ...            ...
101681  fffc94f6ce00a00581880bf54a75a037       boleto     343.399994
101682  fffcd46ef2263f404302a634eb57f7eb       boleto     386.529999
101683  fffce4705a9662cd70adb13d4a31832d  credit_card     116.849998
101684  fffe18544ffabc95dfada21779c9644f  credit_card      64.709999
101685  fffe41c64501cc87c801fd61db3f6244  credit_card      55.790001

[101686 rows x 3 columns]

In [117]:
payments[payments["order_id"]=="fa65dad1b0e818e3ccc5cb0e39231352"]

                               order_id payment_type  payment_value
99453  fa65dad1b0e818e3ccc5cb0e39231352      voucher     457.989998

In [118]:
payments.shape

(101686, 3)

In [119]:
payments.head()

                           order_id payment_type  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214  credit_card      72.190002
1  00018f77f2f0320c557190d7a144bdd3  credit_card     259.829987
2  000229ec398224ef6ca0657da4fc703e  credit_card     216.869995
3  00024acbcdf0a6daa1e931b038114c75  credit_card      25.780001
4  00042b26cf59d7ce69dfabb4e55b4fd9  credit_card     218.039993

In [120]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [121]:
print(orders["order_id"].nunique())
print(payments["order_id"].nunique())

96279
99440

In [122]:
# orders - cancelled -- payments id --- payment 
# orders - rows cleaned -- payemnts_id -- payment 
# orders -- payment
# payment -- orders

In [123]:
len(orders[orders["order_status"]=="canceled"])

69

In [124]:
orders[~orders["order_id"].isin(payments["order_id"])]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04

In [125]:
payments[~payments["order_id"].isin(orders["order_id"])]["order_id"].nunique()

3162

In [126]:
#orders -- cleaned
# df --- uncleaned

In [127]:
# df- 1000
# orders- 890
# cleaning - 110 order id

In [128]:
df[~df["order_id"].isin(orders["order_id"])]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04
64,688052146432ef8253587b930b01a06d,81e08b08e5ed4472008030d70327c71f,delivered,2018-04-22 08:48:13,2018-04-24 18:25:22,2018-04-23 19:19:14,2018-04-24 19:31:58,2018-05-15
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaT,NaT,2018-08-21
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaT,NaT,2017-10-03
...,...,...,...,...,...,...,...,...
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaT,NaT,NaT,2018-09-27
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaT,NaT,2017-09-15
99377,a6bd1f93b7ff72cc348ca07f38ec4bee,6d63fa86bd2f62908ad328325799152f,delivered,2018-04-20 17:28:40,2018-04-24 19:26:10,2018-04-23 17:18:40,2018-04-28 17:38:42,2018-05-15
99406,7fd85cb0143de098a4c5ab5a57bfbd91,d32034dfc685b1ae15dd4c78eace868e,delivered,2017-05-04 21:05:28,2017-05-09 22:33:28,2017-05-09 17:02:58,2017-05-18 06:34:38,2017-06-01
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaT,NaT,2017-10-23

In [129]:
# df---- orders    --- 3162 orders id

In [130]:
payments , orders

(                                order_id payment_type  payment_value
 0       00010242fe8c5a6d1ba2dd792cb16214  credit_card      72.190002
 1       00018f77f2f0320c557190d7a144bdd3  credit_card     259.829987
 2       000229ec398224ef6ca0657da4fc703e  credit_card     216.869995
 3       00024acbcdf0a6daa1e931b038114c75  credit_card      25.780001
 4       00042b26cf59d7ce69dfabb4e55b4fd9  credit_card     218.039993
 ...                                  ...          ...            ...
 101681  fffc94f6ce00a00581880bf54a75a037       boleto     343.399994
 101682  fffcd46ef2263f404302a634eb57f7eb       boleto     386.529999
 101683  fffce4705a9662cd70adb13d4a31832d  credit_card     116.849998
 101684  fffe18544ffabc95dfada21779c9644f  credit_card      64.709999
 101685  fffe41c64501cc87c801fd61db3f6244  credit_card      55.790001

 [101686 rows x 3 columns],
                                order_id                       customer_id  \
 0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
 1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
 2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
 3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
 4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
 ...                                 ...                               ...
 99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
 99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
 99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
 99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
 99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

       order_status order_purchase_timestamp   order_approved_at  \
 0        delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
 1        delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
 2        delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
 3        delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
 4        delivered      2018-02-13 21:18:39 2018-02-13 22:20:29
 ...            ...                      ...                 ...
 99436    delivered      2017-03-09 09:54:05 2017-03-09 09:54:05
 99437    delivered      2018-02-06 12:58:58 2018-02-06 13:10:37
 99438    delivered      2017-08-27 14:46:43 2017-08-27 15:04:16
 99439    delivered      2018-01-08 21:28:27 2018-01-08 21:36:21
 99440    delivered      2018-03-08 20:57:30 2018-03-09 11:20:28

       order_delivered_carrier_date order_delivered_customer_date  \
 0              2017-10-04 19:55:00           2017-10-10 21:25:13
 1              2018-07-26 14:31:00           2018-08-07 15:27:45
 2              2018-08-08 13:50:00           2018-08-17 18:06:29
 3              2017-11-22 13:39:59           2017-12-02 00:28:42
 4              2018-02-14 19:46:34           2018-02-16 18:17:02
 ...                            ...                           ...
 99436          2017-03-10 11:18:03           2017-03-17 15:08:01
 99437          2018-02-07 23:22:42           2018-02-28 17:37:56
 99438          2017-08-28 20:52:26           2017-09-21 11:24:17
 99439          2018-01-12 15:35:03           2018-01-25 23:32:54
 99440          2018-03-09 22:11:59           2018-03-16 13:08:30

       order_estimated_delivery_date
 0                        2017-10-18
 1                        2018-08-13
 2                        2018-09-04
 3                        2017-12-15
 4                        2018-02-26
 ...                             ...
 99436                    2017-03-28
 99437                    2018-03-02
 99438                    2017-09-27
 99439                    2018-02-15
 99440                    2018-04-03

 [96279 rows x 8 columns])

In [131]:
orders=pd.merge(orders,payments,on="order_id",how="inner")

In [132]:
orders["order_id"].nunique()

96278

In [133]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.460007
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.119995
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.199997
...,...,...,...,...,...,...,...,...,...,...
98444,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,credit_card,85.080002
98445,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.000000
98446,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.010010
98447,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004
98448,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.860001

### olist_order_items_dataset

In [135]:
query ="select * from olist_order_items_dataset"
olist_items= pd.read_sql(query, conn)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\830416410.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  olist_items= pd.read_sql(query, conn)

In [136]:
olist_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.990000,12.790000
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.899994,18.139999
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.989990,43.410000
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.000000,36.529999
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.900002,16.950001
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.990002,8.720000
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.000000,12.790000

In [137]:
print(orders["order_id"].nunique())
print(olist_items["order_id"].nunique())

96278
98666

In [138]:
#merge -- inner join

In [139]:
orders= pd.merge(orders, olist_items, on="order_id", how="inner")

In [140]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.460007,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.699997,22.760000
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.119995,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.899994,19.219999
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.199997,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.000000,27.200001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.000000,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.899994,20.100000
112306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.010010,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.990005,65.019997
112307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.860001,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.500000,18.360001

In [141]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112310 entries, 0 to 112309
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112310 non-null  object
 1   customer_id                    112310 non-null  object
 2   order_status                   112310 non-null  object
 3   order_purchase_timestamp       112310 non-null  datetime64[ns]
 4   order_approved_at              112310 non-null  datetime64[ns]
 5   order_delivered_carrier_date   112310 non-null  datetime64[ns]
 6   order_delivered_customer_date  111039 non-null  datetime64[ns]
 7   order_estimated_delivery_date  112310 non-null  datetime64[ns]
 8   payment_type                   112310 non-null  object
 9   payment_value                  112310 non-null  float64
 10  order_item_id                  112310 non-null  int64
 11  product_id                     112310 non-null  object
 12  seller_id                      112310 non-null  object
 13  shipping_limit_date            112310 non-null  datetime64[ns]
 14  price                          112310 non-null  float64
 15  freight_value                  112310 non-null  float64
dtypes: datetime64[ns](6), float64(3), int64(1), object(6)
memory usage: 13.7+ MB

In [142]:
orders= orders[(orders["shipping_limit_date"]>orders["order_purchase_timestamp"]) &
(orders["shipping_limit_date"]>orders["order_approved_at"])&
(orders["shipping_limit_date"]<orders["order_delivered_customer_date"])]

In [143]:
orders.sort_values(by=["order_item_id","order_id"], ascending=False)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
100242,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,21,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.800000,6.570000
106170,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,20,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.440000
100241,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,20,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.200000,7.890000
98128,1b15974a0141d54e36626dca3fdc731a,be1b70680b9f9694d8c70f41fa3dc92b,delivered,2018-02-22 15:30:41,2018-02-24 03:20:27,2018-03-02 00:18:01,2018-03-05 15:22:27,2018-03-08,boleto,2202.399902,20,ee3d532c8a438679776d222e997606b3,8e6d7754bc7e0f22c96d255ebda59eba,2018-03-01 02:50:48,100.000000,10.120000
106169,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,19,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.440000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111297,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,delivered,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,credit_card,31.750000,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.900000,11.850000
5863,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,credit_card,218.039993,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.899994,18.139999
7056,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,credit_card,216.869995,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001
81124,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,credit_card,259.829987,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000
96209,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,credit_card,72.190002,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000

In [144]:
orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
100222,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,1,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100223,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,2,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100224,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,3,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100225,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,4,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100226,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,5,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100227,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,6,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100228,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,7,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100229,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,8,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100230,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,9,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100231,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,10,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100232,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,11,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100233,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,12,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100234,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,13,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100235,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,14,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100236,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,15,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100237,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,16,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100238,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,17,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100239,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,18,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100240,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,19,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100241,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,20,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100242,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,21,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.8,6.57

In [145]:
sum(orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]["price"]+orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]["freight_value"])

196.16999864578247

In [146]:
orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
100222,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,1,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100223,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,2,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100224,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,3,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100225,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,4,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100226,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,5,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100227,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,6,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100228,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,7,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100229,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,8,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100230,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,9,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100231,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,10,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100232,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,11,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100233,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,12,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100234,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,13,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100235,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,14,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100236,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,15,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100237,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,16,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100238,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,17,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100239,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,18,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100240,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,19,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100241,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,20,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100242,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,21,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.8,6.57

In [147]:
orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
106151,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,1,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106152,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,2,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106153,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,3,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106154,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,4,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106155,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,5,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106156,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,6,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106157,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,7,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106158,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,8,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106159,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,9,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106160,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,10,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106161,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,11,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106162,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,12,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106163,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,13,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106164,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,14,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106165,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,15,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106166,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,16,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106167,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,17,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106168,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,18,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106169,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,19,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44
106170,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,20,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.44

In [148]:
sum(orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]["price"]+orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]["freight_value"])

2262.7999305725098

In [149]:
orders.drop(columns="order_item_id", inplace=True)

C:\Users\aryan\AppData\Local\Temp\ipykernel_5572\377052281.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders.drop(columns="order_item_id", inplace=True)

In [150]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [151]:
orders= orders.groupby(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date']).agg(price=("price", "sum"),
                                   freight_value=("freight_value", "sum"),
                                   Quantity=("product_id","count")).reset_index()

In [152]:
orders.sort_values(by="Quantity", ascending=False)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
53512,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,1973.999939,288.799992,20
8496,1b15974a0141d54e36626dca3fdc731a,be1b70680b9f9694d8c70f41fa3dc92b,delivered,2018-02-22 15:30:41,2018-02-24 03:20:27,2018-03-02 00:18:01,2018-03-05 15:22:27,2018-03-08,boleto,2202.399902,ee3d532c8a438679776d222e997606b3,8e6d7754bc7e0f22c96d255ebda59eba,2018-03-01 02:50:48,2000.000000,202.399998,20
20773,428a2f660dc84138d969ccd69a0ab6d5,10de381f8a8d23fff822753305f71cae,delivered,2017-11-23 20:30:52,2017-11-24 10:31:10,2017-11-28 16:42:21,2017-12-13 20:19:35,2017-12-19,credit_card,1225.650024,89b190a046022486c635022524a974a8,f326006815956455b2859abd58fe7e39,2017-11-30 10:30:51,982.349968,243.299990,15
49598,9ef13efd6949e4573a18964dd1bbe7f5,adb32467ecc74b53576d9d13a5a55891,delivered,2017-01-30 21:44:49,2017-01-30 22:33:45,2017-02-01 14:34:10,2017-02-14 10:48:10,2017-03-07,credit_card,783.000000,37eb69aca8718e843d897aa7b82f462d,0b36063d5818f81ccb94b54adfaebbf5,2017-02-03 21:44:49,765.000000,18.000001,15
36295,73c8ab38f07dc94389065f7eba4f297a,d5f2b3f597c7ccafbb5cac0bcc3d6024,delivered,2017-12-13 14:21:15,2017-12-15 02:30:41,2017-12-15 18:45:18,2017-12-28 09:05:34,2018-01-08,boleto,1014.020020,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2017-12-21 02:30:41,826.000000,188.020004,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27717,588e9a3844482484a31e604c2767b82f,c6d04a9495cc4d8e22a4276131aac50e,delivered,2018-03-24 21:50:02,2018-03-27 04:10:23,2018-03-27 22:41:58,2018-04-05 20:56:33,2018-04-24,boleto,94.970001,72d3bf1d3a790f8874096fcf860e3eff,0bae85eb84b9fb3bd773911e89288d54,2018-04-02 04:10:23,42.490002,52.480000,1
27716,588e7e0d12441120556b3eab625514aa,23e0317302b368c4a95fe1b35ab76710,delivered,2017-12-11 15:24:04,2017-12-11 15:34:25,2017-12-15 00:13:46,2017-12-16 14:19:46,2017-12-28,debit_card,74.559998,dffb26377d60bf9bd5bd4cd856e9dbb4,fcb5ace8bcc92f75707dc0f01a27d269,2017-12-15 15:34:25,64.980003,9.580000,1
27715,588d8a3645cd2c4d3b9773d212a185e5,d0c8dedcb2e16a6245f6a9f836385068,delivered,2017-12-10 22:51:43,2017-12-10 23:08:55,2017-12-12 17:57:14,2017-12-26 11:35:05,2018-01-08,credit_card,1223.060059,20332c1e41e427864b3561a657caaf0d,fa1c13f2614d7b5c4749cbc52fecda94,2017-12-14 23:08:55,1199.900024,23.160000,1
27713,588ae5afdb6a80a74e552cb5c59ba7ee,84d7fc1855828ec6618e352ffc20aeaf,delivered,2018-07-05 12:34:36,2018-07-05 16:11:40,2018-07-10 08:26:00,2018-07-13 01:58:45,2018-07-20,credit_card,39.470001,70e0c10acc3dd72e17f2136ddb027317,ce27a3cc3c8cc1ea79d11e561e9bebb6,2018-07-11 13:33:23,31.990000,7.480000,1
80155,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,credit_card,55.790001,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.000000,12.790000,1

In [153]:
orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
53512,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,1973.999939,288.799992,20

In [154]:
orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
40777,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,12.0,78.899999,10
40778,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,12.0,78.899999,10
40779,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.8,6.570000,1

In [155]:
orders.shape

(80156, 16)

In [156]:
pd.merge(orders, customers, left_on="customer_id", right_on="customer_id",how="inner")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,credit_card,72.190002,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000,1,871766c5855e863f6eccc05f988b23cb,28013,Campos Dos Goytacazes,RJ
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,credit_card,259.829987,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000,1,eb28e67c4c0b83846050ddfb8a35d051,15775,Santa Fe Do Sul,SP
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,credit_card,216.869995,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001,1,3818d81c6709e39d06b2738a8d3a2474,35661,Para De Minas,MG
3,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,credit_card,218.039993,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.899994,18.139999,1,64b576fb70d441e8f1b2d7d446e483c5,13226,Varzea Paulista,SP
4,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,delivered,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,credit_card,31.750000,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.900000,11.850000,1,635d9ac1680f03288e72ada3a1035803,16700,Guararapes,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80151,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,boleto,356.760010,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,220.000000,136.759995,4,f736308cd9952b33b90b9fe94da9c8f5,56912,Serra Talhada,PE
80152,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,delivered,2018-06-19 09:27:48,2018-06-19 09:58:03,2018-06-29 13:46:00,2018-07-05 17:51:08,2018-07-23,credit_card,139.880005,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.849998,20.030001,1,ecc3d4eb9b17d2f0865d21f2abecc51c,39401,Montes Claros,MG
80153,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,boleto,343.399994,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.989990,43.410000,1,0c9aeda10a71f369396d0c04dce13a64,65077,Sao Luis,MA
80154,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,boleto,386.529999,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.000000,36.529999,1,0da9fe112eae0c74d3ba1fe16de0988b,81690,Curitiba,PR
80155,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,credit_card,55.790001,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.000000,12.790000,1,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,18605,Botucatu,SP

In [157]:
customers.drop(columns="customer_unique_id", inplace=True)

In [158]:
customers

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,6273,Osasco,SP
1,000161a058600d5901f007fab4c27140,35550,Itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,29830,Nova Venecia,ES
3,0002414f95344307404f0ace7a26f1d5,39664,Mendonca,MG
4,000379cdec625522490c315e70c7a9fb,4841,Sao Paulo,SP
...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,95630,Parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,22461,Rio De Janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,6754,Taboao Da Serra,SP
99439,ffffa3172527f765de70084a7e53aae8,37130,Alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,6172,Osasco,SP